# Generated by Django 4.0.5 on 2022-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carlist',
            fields=[
                ('BrandName', models.CharField(max_length=100)),
                ('ModelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Fuels', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
